[tool.poetry]
name = "certipie"
version = "0.1.0"
description = "A tool to create csr and auto-certificate"
authors = ["le_woudar <kevin.tewouda@gandi.net>"]
license = "Apache 2"

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.73.0"
click = "^8.0.3"
cryptography = "^36.0.1"
hypercorn = "^0.13.2"

[tool.poetry.dev-dependencies]
pytest = "^7.0.0"
pytest-cov = "^3.0.0"
bandit = "^1.7.2"
flake8 = "^4.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
